<a href="https://colab.research.google.com/github/deepan98raj-dotcom/My_Project/blob/main/Hugging_face_speach_to_text.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install transformers

In [2]:
from transformers import pipeline

In [3]:
import transformers
print(transformers.__version__)

5.17.0


In [7]:
import librosa
import torch
import IPython.display as display
from transformers import Wav2Vec2ForCTC, Wav2Vec2Processor
import numpy as np

In [8]:
tokenizer = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

preprocessor_config.json:   0%|          | 0.00/159 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.60k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/163 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/291 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  378MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/212 [00:00<?, ?it/s]

[transformers] Wav2Vec2ForCTC LOAD REPORT from: facebook/wav2vec2-base-960h
Key                        | Status  | 
---------------------------+---------+-
wav2vec2.masked_spec_embed | MISSING | 

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


In [11]:
from google.colab import files

uploaded = files.upload()
# This will prompt you to select your file. Once uploaded, 'v.m4a' will be available in your directory.

Saving v.m4a.m4a to v.m4a.m4a


In [13]:
audio, sampling_rate = librosa.load('v.m4a.m4a', sr=16000)

/tmp/ipykernel_6424/2944357467.py:1: UserWarning: PySoundFile failed. Trying audioread instead.
  audio, sampling_rate = librosa.load('v.m4a.m4a', sr=16000)
/usr/local/lib/python3.13/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)


In [14]:
audio,sampling_rate

(array([-1.3156350e-04, -2.7711951e-04, -1.6768856e-04, ...,
         1.6182541e-05,  3.8679733e-05,  0.0000000e+00], dtype=float32),
 16000)

In [15]:
display.Audio('v.m4a.m4a', autoplay=True)

In [16]:
input_values = tokenizer(audio, return_tensors="pt").input_values
input_values

[transformers] It is strongly recommended to pass the `sampling_rate` argument to `Wav2Vec2FeatureExtractor()`. Failing to do so can result in silent errors that might be hard to debug.


tensor([[-0.0006, -0.0028, -0.0012,  ...,  0.0016,  0.0019,  0.0014]])

In [18]:
logits = model(input_values).logits
logits

tensor([[[ 13.0122, -26.2826, -26.0877,  ...,  -5.8864,  -6.3110,  -7.6709],
         [  7.8293, -21.3323, -21.2295,  ...,  -2.9450,  -5.4155,  -6.1603],
         [  7.5844, -19.8792, -19.7612,  ...,  -1.8123,  -5.2551,  -6.9900],
         ...,
         [ 15.6356, -29.5243, -29.1534,  ...,  -6.1570,  -8.8353,  -7.3639],
         [ 15.4478, -29.4873, -29.1268,  ...,  -6.2598,  -8.7599,  -7.5972],
         [ 15.1869, -29.1087, -28.7445,  ...,  -6.0155,  -8.7530,  -7.5257]]],
       grad_fn=<ViewBackward0>)

In [19]:
predicted_ids = torch.argmax(logits, dim=-1)
predicted_ids

tensor([[ 0, 11, 11,  ...,  0,  0,  0]])

In [20]:
transcription = tokenizer.batch_decode(predicted_ids)[0]
transcription

"HIGH THERE THIS IS A SAMPLE VOICE RECORDING CREATED FOR SPEECH SYNTHESIS TESTING THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG JUST A FUN WAY TO INCLUDE EVERY LETTER OF THE ALPHABET NUMBERS LIKE ONE TWO THREE ARE SPOKEN CLEARLY LET'S SEE HOW WELL THIS VOICE CAPTURES TONE TIMING AND NATURAL RHYTHM THIS AUDIO IS PROVIDED BY SAMPLE FILES DAC KOM"