<a href="https://colab.research.google.com/github/deepan98raj-dotcom/My_Project/blob/main/NumPy_%26_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1.NumPy

In [ ]:
import numpy as np

numbers = np.array([1, 2, 3, 4])

print(numbers)

[1 2 3 4]


In [ ]:
print(numbers.dtype)
print(numbers.shape)
print(numbers.ndim)
print(numbers.size)
print(numbers*5)

int64
(4,)
1
4
[ 5 10 15 20]


### Index

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[2])
print(arr[-1])

10
30
50


In [ ]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr[0, 1])

20


### Slicing

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])

[20 30 40]


### Mathematical operations

In [ ]:
arr = np.array([10, 20, 30, 40])

print(arr + 5)
print(arr - 5)
print(arr * 2)
print(arr / 2)

[15 25 35 45]
[ 5 15 25 35]
[20 40 60 80]
[ 5. 10. 15. 20.]


### NumPy Funtions

In [ ]:
arr = np.zeros(5)

print(arr)

[0. 0. 0. 0. 0.]


In [ ]:
arr = np.ones(5)

print(arr)

[1. 1. 1. 1. 1.]


In [ ]:
arr = np.arange(1, 10)

print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.linspace(0, 3, 5)

print(arr)

[0.   0.75 1.5  2.25 3.  ]


In [ ]:
arr = np.random.rand(5)

print(arr)

[0.11845468 0.50415169 0.04591476 0.88592003 0.04033749]


In [ ]:
arr = np.random.randint(1, 10, 5)

print(arr)

[7 4 4 9 3]


### Mean,Median,Maximum,Minimum

In [ ]:
marks = np.array([70, 80, 90, 60, 100])
print(np.mean(marks))
print(np.median(marks))
print(np.std(marks))
print(np.max(marks))
print(np.min(marks))
print(np.sum(marks))

80.0
80.0
14.142135623730951
100
60
400


### Flatten

In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

new_arr = arr.flatten()

print(new_arr)

[1 2 3 4 5 6]


### Axis (0,1)

In [ ]:
data = np.array([
    [20, 50000, 2],
    [30, 60000, 5],
    [40, 80000, 10]
])

In [ ]:
mean_values = data.mean(axis=0)

print(mean_values)

[3.00000000e+01 6.33333333e+04 5.66666667e+00]


In [ ]:
mean_values = data.mean(axis=1)

print(mean_values)

[16674.         20011.66666667 26683.33333333]


In [ ]:
predictions = np.array([
    [0.1, 0.7, 0.2],
    [0.8, 0.1, 0.1],
    [0.2, 0.2, 0.6]
])

classes = np.argmax(predictions, axis=1)

print(classes)

[1 0 2]


### Normalization

In [ ]:


data = np.array([0, 50, 100, 150, 200, 250])

normalized = data / 250

print(normalized)

[0.  0.2 0.4 0.6 0.8 1. ]


### Standardization

In [ ]:


data = np.array([10, 20, 30, 40, 50])

mean = np.mean(data)
std = np.std(data)

standardized = (data - mean) / std

print(standardized)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


### seed random

In [ ]:
np.random.seed(42)

data = np.random.randint(1, 101, 10)

print(data)

[52 93 15 72 61 21 83 87 75 75]


In [ ]:
rng = np.random.default_rng(42)

numbers = rng.random(5)

print(numbers)

[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.concatenate((a, b))

print(result)

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.vstack((a, b))

print(result)

[[1 2 3]
 [4 5 6]]


In [ ]:
age = np.array([25, 30, 35])
salary = np.array([40000, 50000, 60000])

g = np.stack((age, salary), axis=1)

print(g)

[[   25 40000]
 [   30 50000]
 [   35 60000]]


In [ ]:
data = np.array([10, 20, np.nan, 40, 50])

data[np.isnan(data)] = 0

print(data)

[10. 20.  0. 40. 50.]


In [ ]:
data = np.array([10, 20, np.nan, 40, 50])

mean_value = np.nanmean(data)

data[np.isnan(data)] = mean_value

print(data)

[10. 20. 30. 40. 50.]


In [ ]:
data = np.array([
    [10, 20, 30],
    [40, np.nan, 60],
    [70, 80, 90]
])

print(np.isnan(data))

[[False False False]
 [False  True False]
 [False False False]]


# 2.Pandas

In [ ]:
import pandas as pd

data = {
    "name": ["Deepan", "Raj"],
    "age": [28, 30],
    'city': ['Chennai', 'Bangalore'],
    'is_student': [True, False],
    'qulification' : ['B.Tech', 'M.Tech']
}

df = pd.DataFrame(data)

print(df)

     name  age       city  is_student qulification
0  Deepan   28    Chennai        True       B.Tech
1     Raj   30  Bangalore       False       M.Tech


In [ ]:
file = open("example.txt", "w")
file.close()

In [ ]:
file = open("example.txt", "w")

file.write("Hello, Deepan!")

file.close()

In [ ]:
with open("example.txt", "w") as file:
    file.write("Hello, Deepan!")

print("File created successfully")

File created successfully


In [ ]:
file.close()

In [ ]:
with open("skills.txt", "w") as file:
    file.write("Python\n")
    file.write("SQL\n")
    file.write("Machine Learning\n")
    file.write("Generative AI\n")

In [ ]:
skills = [
    "Python\n",
    "SQL\n",
    "Machine Learning\n",
    "Generative AI\n"
]

with open("skills.txt", "w") as file:
    file.writelines(skills)

In [ ]:
with open("skills.txt", "w") as file:
    file.write("Generative AI")

In [ ]:
import os

# Create the 'data' directory if it doesn't already exist
os.makedirs('data', exist_ok=True)

with open("data/student.txt", "w") as file:
    file.write("Deepan")

In [ ]:
prompt = "Explain Generative AI in simple words."

with open("prompt.txt", "w") as file:
    file.write(prompt)

print("Prompt saved")

Prompt saved


In [ ]:
with open("filename.txt", "w") as file:
    file.write("Your content")

In [ ]:
with open("example.txt", "r") as file:
    content = file.read()

print(content)

Hello, Deepan!


In [ ]:
with open("data.txt", "w") as file:
    file.write("This is some sample data.")

with open("data.txt", "r") as file:
    content = file.read()

print(content)

This is some sample data.


In [ ]:
open("data.txt", "r")

<_io.TextIOWrapper name='data.txt' mode='r' encoding='utf-8'>

In [ ]:
with open("data.txt", "r") as file:
    line = file.readline()

print(line)

This is some sample data.


In [ ]:
with open("data.txt", "r") as file:
    lines = file.readlines()

print(lines)

['This is some sample data.']


In [ ]:
with open("data.txt", "w") as file:
    file.write("Python\n")
    file.write("Machine Learning\n")
    file.write("Generative AI\n")

In [ ]:
with open("data.txt", "a") as file:
    file.write("\nGenerative AI")

In [ ]:
import csv


with open("employees.csv", "r") as file:
    reader = csv.reader(file)

    for row in reader:
        print(row)


['name', 'age', 'role']
['John', '25', 'Developer']
['David', '28', 'Tester']
['Sarah', '30', 'AI Engineer']
['Ajith', '28', 'Software Engineer']
['Michael', '32', 'Data Scientist']


In [ ]:
import csv

data = [
    ["name", "age", "role"],
    ["John", 25, "Developer"],
    ["David", 28, "Tester"],
    ["Sarah", 30, "AI Engineer"]
]

with open("employees.csv", "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerows(data)

In [ ]:
import csv

with open("employees.csv", "a", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(['Ajith', 28, 'Software Engineer'])

In [ ]:
import csv

with open("employees.csv", "a", newline="") as file:
    writer = csv.writer(file)

    writer.writerow(["Michael", 32, "Data Scientist"])
    print(row)

['Michael', '32', 'Data Scientist']


In [ ]:
import csv

with open("employees.csv", "r") as file:

    reader = csv.DictReader(file)

    for row in reader:
        print(row["name"])
        print(row["role"])

John
Developer
David
Tester
Sarah
AI Engineer
Ajith
Software Engineer
Michael
Data Scientist


In [ ]:
import json

data = {
    "name": "John",
    "age": 28,
    "skills": ["Python", "SQL", "AI"]
}

with open("employee.json", "w") as file:
    json.dump(data, file, indent=4)

In [ ]:
with open("employee.json", "r") as file:
    data = json.load(file)

print(data)

{'name': 'John', 'age': 28, 'skills': ['Python', 'SQL', 'AI']}
